### ISSUE TITLE
give detailed instructions on how to setup the server

### ISSUE THREAD

**Issue by mojo2012** [jonls/php-git-server#1]
Hi,

I currently run a web server with php and mysql and nothing else (no root server) and want to setup a version control system.
I found your php git server and it seems that this is the thing I want.

But how do I correctly set it up? What to put into the config.php in the $repos array?

How to "git init" a new repo and stuff like this?

**Comment by jonls** [comment]
It's been a while since i wrote this so let me see if i can remember: You create a git repo locally with git init. Let's say you've created it in "/home/project/". Then you push only the "/home/project/.git" directory to your server somewhere with e.g. ftp or rsync. You may want to rename it to something else, like "project.git". So, let's say you've uploaded it to the server with the path "/server/www/git/project.git". Then you could drop the index.php and config.php in "/server/www/git/" and setup the $repos in config.php with $repos = array(array('/project.git', 'project.git'));. If for example your server is http://example.com, serving from "/server/www/", then your project will be available for git cloning at http://example.com/git/project.git . The first parameter in the $repos[0] array is the public url postfix, the second parameter is the local path to the ".git" directory.

Let me know if this makes sense, and I'll update the README file.
